export enum ApartmentType {
  APARTMENT_GET_LIST_REQUEST = 'apartment/APARTMENT_GET_LIST_REQUEST',
  APARTMENT_GET_LIST_SUCCESS = 'apartment/APARTMENT_GET_LIST_SUCCESS',
  APARTMENT_GET_LIST_FAILURE = 'apartment/APARTMENT_GET_LIST_FAILURE',
};
